default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: library_development
  
test:
  <<: *default
  database: library_test

production:
  <<: *default
  database: library_production
